name: build-test

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        dotnet: ['3.1.201', '3.1.101']
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      NUGET_XMLDOC_MODE: skip
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core ${{ matrix.dotnet }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
    # build
    - run: dotnet build ./src/MagicOnion/ -c Debug
    - run: dotnet build ./src/MagicOnion.Abstractions/ -c Debug
    - run: dotnet build ./src/MagicOnion.Hosting/ -c Debug
    - run: dotnet build ./src/MagicOnion.HttpGateway/ -c Debug
    - run: dotnet build ./src/MagicOnion.Redis/ -c Debug
    - run: dotnet build ./src/MagicOnion.OpenTelemetry/ -c Debug
    - run: dotnet build ./src/MagicOnion.MSBuild.Tasks/ -c Debug
    - run: dotnet build ./src/MagicOnion.Generator/ -c Debug
    - run: dotnet build ./src/MagicOnion.Server.Authentication/ -c Debug
    - run: dotnet build ./src/MagicOnion.OpenTelemetry/ -c Debug
    # test
    - run: dotnet test ./tests/MagicOnion.NetCoreTests/ -c Debug
    - run: dotnet test ./tests/MagicOnion.Hosting.Tests/ -c Debug

